sonar.projectKey=letterbook
sonar.organization=letterbook
sonar.sources=backend/src/main
sonar.tests=backend/src/test
sonar.java.binaries=backend/target/classes
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.exclusions=**/LetterbookApplication.java,frontend/**
