name: CI

on:
  push:
    branches: [ main, develop, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    name: Build, Test, JaCoCo & SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Ajustar permissão e rodar Build/Testes
        run: |
          chmod +x backend/mvnw
          ./backend/mvnw -B clean verify

      - name: Upload JaCoCo report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: backend/target/site/jacoco/

      - name: SonarCloud Scan
        if: ${{ env.SONAR_TOKEN != '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./backend/mvnw -B sonar:sonar \
          -Dsonar.projectKey=letterbook \
          -Dsonar.organization=letterbook \
          -Dsonar.host.url=https://sonarcloud.io